"""
Pydantic request / response models for the DTS Scoring API.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


# ── Request ──────────────────────────────────────────────────────────────────

class ScoreRequest(BaseModel):
    """Payload sent to POST /score"""

    prompt: str = Field(
        ...,
        description="The input prompt to score. The model will generate a response "
                    "and DTS is computed over that response's tokens.",
        examples=["What are the baggage allowance rules for economy class?"],
    )
    max_new_tokens: int = Field(
        default=100,
        ge=1,
        le=512,
        description="Maximum response tokens to generate (and score).",
    )
    settling_threshold: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="JSD threshold below which a token is considered 'settled' (g).",
    )
    depth_fraction: float = Field(
        default=0.85,
        ge=0.0,
        le=1.0,
        description="Fraction of layers; tokens settling at or after this depth are "
                    "labelled deep-thinking (ρ).",
    )
    max_prompt_tokens: int = Field(
        default=512,
        ge=64,
        le=2048,
        description="Truncate the prompt to this many tokens before scoring. "
                    "Reduces GPU memory for long prompts (each token needs a full "
                    "forward pass × 32 layers). Default 512 is safe for 16 GB VRAM.",
    )
    include_jsd_trace: bool = Field(
        default=False,
        description="If true, include per-layer JSD distances for every token in the "
                    "response. Useful for debugging; increases payload size.",
    )


# ── Per-token detail ──────────────────────────────────────────────────────────

class TokenDetail(BaseModel):
    """Metrics for a single response token."""

    position: int = Field(description="0-based index in the generated response.")
    token: str = Field(description="Decoded text of the token.")
    token_id: int = Field(description="Vocabulary ID of the token.")
    settling_layer: int = Field(
        description="First layer (c_t) where the running-minimum JSD dropped below the "
                    "settling threshold."
    )
    settling_depth_fraction: float = Field(
        description="settling_layer / num_layers — position relative to model depth."
    )
    is_deep: bool = Field(
        description="True when the token settled only in the deepest (1-ρ)·100 % of layers."
    )
    jsd_trace: Optional[List[float]] = Field(
        default=None,
        description="JSD distance from final prediction at each transformer layer. "
                    "Only populated when include_jsd_trace=true.",
    )


# ── Response ──────────────────────────────────────────────────────────────────

class ScoreResponse(BaseModel):
    """Full DTS scoring result returned by POST /score."""

    # ── Top-level score ───────────────────────────────────────────────────────
    dts_score: float = Field(
        description="Deep Thinking Score ∈ [0, 1]. Fraction of response tokens that "
                    "required deep-layer settling."
    )
    category: str = Field(
        description="Calibrated label: 'Shallow' (<0.3), 'Moderate' (0.3–0.7), 'Deep' (≥0.7)."
    )

    # ── Response text ─────────────────────────────────────────────────────────
    generated_response: str = Field(
        description="Text generated by the model for the given prompt."
    )
    total_tokens: int = Field(description="Number of tokens in the generated response.")

    # ── Aggregate settling metrics ────────────────────────────────────────────
    avg_settling_depth: float = Field(
        description="Mean settling layer (c̄) across all response tokens."
    )
    settling_depth_fraction: float = Field(
        description="avg_settling_depth / num_layers — comparable across model sizes."
    )
    num_deep_tokens: int = Field(description="Absolute count of deep-thinking tokens.")

    # ── Per-token detail ──────────────────────────────────────────────────────
    deep_tokens: List[TokenDetail] = Field(
        description="Details for every token that required deep-layer computation "
                    "(is_deep=True). Sorted by position."
    )
    all_tokens: List[TokenDetail] = Field(
        description="Details for ALL response tokens (shallow + deep), in order."
    )

    # ── Run config ────────────────────────────────────────────────────────────
    model_name: str = Field(description="HuggingFace model identifier used for scoring.")
    num_layers: int = Field(description="Number of transformer layers in the model.")
    deep_layer_threshold: int = Field(
        description="First layer index counted as 'deep' = ceil(ρ · num_layers)."
    )
    settling_threshold: float = Field(description="JSD settling threshold (g) used.")
    depth_fraction: float = Field(description="Depth fraction (ρ) used.")


# ── Health check ──────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    model_name: str
    device: str
    num_layers: int
